name: sirenhead_test
description: Fake Call App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  google_mobile_ads: ^3.0.0


  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  camera: ^0.10.4
  permission_handler: ^10.2.0
  video_player: ^2.6.1
  url_launcher: ^6.1.10
  firebase_crashlytics: ^3.1.0
  firebase_analytics: ^10.2.1
  shared_preferences: ^2.1.0
  easy_localization: ^3.0.1
  change_app_package_name: ^1.1.0
  clever_ads_solutions: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/icons/
     - assets/videos/
     - assets/audio/
     - assets/translations/


